apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: udash_urtmp-rollout
spec:
  replicas: 5
  selector:
    matchLabels:
      app: udash_urtmp
  template:
    metadata:
      labels:
        app: udash_urtmp
    spec:
      containers:
      - name: udash_urtmp
        image: localhost:80/udash_urtmp:latest
        ports:
        - containerPort: 5858
  minReadySeconds: 30
  revisionHistoryLimit: 3
  strategy:
    canary: #Indicates that the rollout should use the Canary strategy
      maxSurge: "25%"
      maxUnavailable: 0
      steps:
      - setWeight: 10
      - pause:
          duration: 1h # 1 hour
      - setWeight: 20
      - pause: {} # pause indefinitely
