apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: udash_urtmp-rollout
spec:
  replicas: 5
  selector:
    matchLabels:
      app: udash_urtmp
  template:
    metadata:
      labels:
        app: udash_urtmp
    spec:
      hostNetwork: true
      containers:
        - name: udash_urtmp
        image: ec2-52-78-226-224.ap-northeast-2.compute.amazonaws.com:1443/ustream/udash-urtmp
      imagePullSecrets:
        - name: harbor
  minReadySeconds: 30
  revisionHistoryLimit: 3
  strategy:
    canary: #Indicates that the rollout should use the Canary strategy
      maxSurge: "25%"
      maxUnavailable: 0
      steps:
        - setWeight: 10
        - pause:
            duration: 1h # 1 hour
        - setWeight: 20
        - pause: {} # pause indefinitely
